FROM node:20-slim
RUN apt-get update && apt-get install -y ffmpeg && rm -rf /var/lib/apt/lists/*
WORKDIR /app

# Ensure we include devDependencies
COPY package*.json ./
RUN npm install 

# Add node_modules/.bin to PATH so 'concurrently' can be found
ENV PATH /app/node_modules/.bin:$PATH

COPY . .

EXPOSE 3000
EXPOSE 3001

CMD ["npm", "run", "dev"]